---
- hosts: localhost

  vars_files:
    - "index-vars.yml"

  tasks:
    - name: interpolate elasticsearch.yml server configuration
      template: src=elasticsearch.yml.j2 dest=/etc/elasticsearch/elasticsearch.yml
      notify: restart elasticsearch

    - name: elasticsearch | ensure service is running
      service: name=elasticsearch state=started

  handlers:
    - name: restart elasticsearch
      service: name=elasticsearch state=restarted
