---
- hosts: localhost

  vars_files:
    - "index-vars.yml"

  tasks:
    - name: add repo for java 8
      apt_repository: repo='ppa:webupd8team/java' state=present

    - name: set licence selected
      shell: /bin/echo debconf shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections
      sudo: yes

    - name: set licence seen
      shell: /bin/echo debconf shared/accepted-oracle-license-v1-1 seen true | /usr/bin/debconf-set-selections
      sudo: yes

    - name: install java 8
      apt: name=oracle-java8-installer state=latest update-cache=yes force=yes
      sudo: yes

    - name: elasticsearch | add repository key
      apt_key: url=http://packages.elasticsearch.org/GPG-KEY-elasticsearch

    - name: elasticsearch | add repository
      apt_repository: repo='deb http://packages.elasticsearch.org/elasticsearch/{{ es_version }}/debian stable main' update_cache=yes
      tags: elasticsearch

    - name: elasticsearch | install
      apt: pkg=elasticsearch state=latest update_cache=yes

    - name: interpolate elasticsearch.yml server configuration
      template: src=elasticsearch.yml.j2 dest=/etc/elasticsearch/elasticsearch.yml
      notify: restart elasticsearch

    - name: elasticsearch | ensure service is running
      service: name=elasticsearch state=started

  handlers:
    - name: restart elasticsearch
      service: name=elasticsearch state=restarted
