---
- hosts: localhost

  vars_files:
    - "index-vars.yml"

  tasks:
    - name: elasticsearch | add repository key
      apt_key: url=http://packages.elasticsearch.org/GPG-KEY-elasticsearch

    - name: elasticsearch | add repository
      apt_repository: repo='deb http://packages.elasticsearch.org/elasticsearch/{{ es.version }}/debian stable main' update_cache=yes
      tags: elasticsearch

    - name: elasticsearch | install
      apt: pkg=elasticsearch state=latest update_cache=yes

    - name: interpolate elasticsearch.yml server configuration
      template: src=elasticsearch.yml.j2 dest=/etc/elasticsearch/elasticsearch.yml
      notify: restart elasticsearch

    - name: elasticsearch | ensure service is running
      service: name=elasticsearch state=started

  handlers:
    - name: restart elasticsearch
      service: name=elasticsearch state=restarted
